# Generated by Django 5.2.17 on 2026-09-29 06:07

import common.dates
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=common.dates.today)),
                ('payment_type', models.CharField(choices=[('salary', 'Salary'), ('advance', 'Salary Advance'), ('allowance', 'Allowance / Bata')], default='salary', max_length=20)),
                ('salary_month', models.DateField(help_text='Any date in the month this payment belongs to.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fleet.driver')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=common.dates.today)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('other', 'Other')], default='diesel', max_length=20)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate per litre')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_station', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='bookings.booking')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_entries', to='fleet.vehicle')),
            ],
            options={
                'verbose_name_plural': 'fuel entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=common.dates.today)),
                ('income_type', models.CharField(choices=[('trip', 'Trip Income'), ('rental', 'Vehicle Rental'), ('advance', 'Advance'), ('other', 'Other Income')], default='trip', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_booking_advance', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='bookings.booking')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='bookings.customer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=120, verbose_name='Finance company / bank')),
                ('account_number', models.CharField(blank=True, max_length=60, verbose_name='Loan account number')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Interest rate (% per year)')),
                ('start_date', models.DateField()),
                ('tenure_months', models.PositiveSmallIntegerField()),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to calculate automatically.', max_digits=14, null=True)),
                ('first_emi_date', models.DateField(help_text='Due date of the first EMI; later EMIs fall on the same day each month.')),
                ('notes', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EMIInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=14)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.loan')),
            ],
            options={
                'ordering': ['due_date', 'number'],
                'unique_together': {('loan', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=common.dates.today)),
                ('maintenance_type', models.CharField(choices=[('service', 'General Service'), ('repair', 'Repair'), ('oil', 'Oil Change'), ('tyres', 'Tyres'), ('battery', 'Battery'), ('body', 'Body / Paint'), ('breakdown', 'Breakdown'), ('other', 'Other')], default='service', max_length=20)),
                ('workshop', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=common.dates.today)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('driver_salary', 'Driver Salary'), ('toll', 'Toll'), ('parking', 'Parking'), ('insurance', 'Insurance'), ('permit', 'Permit'), ('tax', 'Tax'), ('emi', 'EMI'), ('spare_parts', 'Spare Parts'), ('office', 'Office Expense'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('source', models.CharField(choices=[('manual', 'Entered directly'), ('fuel', 'Fuel entry'), ('maintenance', 'Maintenance'), ('driver', 'Driver payment'), ('emi', 'EMI payment')], default='manual', editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='bookings.booking')),
                ('driver_payment', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='finance.driverpayment')),
                ('installment', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='finance.emiinstallment')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='fleet.vehicle')),
                ('fuel_entry', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='finance.fuelentry')),
                ('maintenance', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='finance.maintenance')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
