# Generated by Django 5.2.17 on 2026-09-29 11:06

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('fleet', '0003_driver_email_driver_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelManagers(
            name='expense',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expenses', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='fuel/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='fuelentry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_reports', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='problem_category',
            field=models.CharField(blank=True, choices=[('engine', 'Engine'), ('tyre', 'Tyre'), ('brake', 'Brake'), ('battery', 'Battery'), ('ac', 'AC'), ('electrical', 'Electrical'), ('body', 'Body'), ('oil', 'Oil'), ('suspension', 'Suspension'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('driver_salary', 'Driver Salary'), ('toll', 'Toll'), ('parking', 'Parking'), ('insurance', 'Insurance'), ('permit', 'Permit'), ('tax', 'Tax'), ('emi', 'EMI'), ('spare_parts', 'Spare Parts'), ('office', 'Office Expense'), ('food_allowance', 'Food Allowance'), ('driver_allowance', 'Driver Allowance'), ('road_expense', 'Road Expense'), ('repair', 'Repair'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=20),
        ),
    ]
