# Generated by Django 5.2.17 on 2026-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('staff', 'Staff'), ('driver', 'Driver')], default='staff', max_length=20),
        ),
    ]
