# Generated by Django 5.2.17 on 2026-09-29 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('short_name', models.CharField(blank=True, help_text="Easy name used in lists and reports, e.g. 'Bus 1' or 'Innova White'.", max_length=40)),
                ('brand', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seating_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('other', 'Other')], default='diesel', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive'), ('sold', 'Sold')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vehicle_type__sort_order', 'short_name', 'registration_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('licence_number', models.CharField(blank=True, max_length=40)),
                ('licence_expiry', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monthly salary')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('insurance', 'Insurance'), ('permit', 'Permit'), ('fitness', 'Fitness Certificate'), ('road_tax', 'Road Tax'), ('pollution', 'Pollution Certificate'), ('rc', 'Registration (RC)'), ('other', 'Other Document')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=60)),
                ('provider', models.CharField(blank=True, help_text='Insurer / issuing office', max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.vehicletype'),
        ),
    ]
