# Generated by Django 5.2.17 on 2026-09-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_assignment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='drivers/'),
        ),
    ]
