# Generated by Django 5.2.17 on 2026-09-29 06:07

import common.dates
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('gst_number', models.CharField(blank=True, max_length=20, verbose_name='GST number')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('booking_date', models.DateField(default=common.dates.today, help_text='Date the booking was taken (advance date).')),
                ('trip_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=150)),
                ('destination', models.CharField(blank=True, max_length=150)),
                ('number_of_days', models.PositiveSmallIntegerField(default=1)),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('advance_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('trip_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='fleet.vehicle')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.customer')),
            ],
            options={
                'ordering': ['-trip_date', '-id'],
            },
        ),
    ]
